### PR TITLE
Fix compilation error.

### PR DESCRIPTION
**Pull request by louib**
@poljar this fixes the compilation errors on my local setup. Let me know if that makes sense.

### CODE REVIEW

**Comment by poljar** [comment]
Thanks, please be aware that the whole executor is moving into the Weechat bindings repo. And the most up to date branches are [this](https://github.com/poljar/weechat-matrix-rs/tree/no_executor) one for weechat-matrix and [this](https://github.com/poljar/rust-weechat/tree/async) one for the Weechat Rust bindings.

There's still some stuff needed in the bindings department, mainly removing unsoundness with the buffer handling, although that's mostly done as well.

After that a release for the bindings is inbound and focus can switch to this beast.

If you're interested I can open issues for stuff that won't clash with that rework and can be safely worked on independently.

**Comment by roket1428** [comment]
Is there any ETA?

**Comment by poljar** [comment]
For which part? Weechat rust bindings, perhaps a week or two. Hard to tell for the rest. Encryption support will have to wait for a couple of months.

**Comment by roket1428** [comment]
> For which part? Weechat rust bindings, perhaps a week or two. Hard to tell for the rest. Encryption support will have to wait for a couple of months.

Directly this git repo.

**Comment by poljar** [comment]
Hard to tell, an initial version that's usable without encryption is still months away. And it's gonna depend on what I'm going to focus on. Probably encryption support.

**Comment by louib** [comment]
> If you're interested I can open issues for stuff that won't clash with that rework and can be safely worked on independently.

@poljar would love that! It'll take me a while to ramp up, but I was definitely thinking about contributing to this project.

**Comment by roket1428** [comment]
> Hard to tell, an initial version that's usable without encryption is still months away. And it's gonna depend on what I'm going to focus on. Probably encryption support.

I think something that usable without encryption support would very great to start but you are the developer. :)

**Comment by poljar** [comment]
> I think something that usable without encryption support would very great to start but you are the developer. :)

Thing is we already have the python script that's pretty usable. But yeah, many things can be worked on independently to the crypto stuff and since we have access to threads, connection pools, async/await the plugin will be mostly free of protocol specifics.

**Comment by roket1428** [comment]
> > I think something that usable without encryption support would very great to start but you are the developer. :)
> 
> Thing is we already have the python script that's pretty usable. But yeah, many things can be worked on independently to the crypto stuff and since we have access to threads, connection pools, async/await the plugin will be mostly free of protocol specifics.

I never get that working. :)

**Comment by poljar** [comment]
I opened now a bunch of issues. More will come. Implementing event formatting would be the easiest one to work on and can be done per event.

**Pull request merged**
