### PR TITLE
Update rust-weechat & matrix-sdk

### PR DESCRIPTION
**Pull request by panekj**
related: https://github.com/poljar/rust-weechat/pull/36

### CODE REVIEW

**Comment by panekj** [comment]
image

**Comment by panekj** [comment]
Still going through some panics but slowly resolving them

**Comment by panekj** [comment]
I'll document some things I had to deal with

crash in hashbrown/map, this one happens due to sheer amount of loaded users when using `MembershipType::JOINED | MembershipType::ACTIVE` in room sync, using just `ACTIVE` works fine (so far)
```
(lldb) bt
* thread #1, name = 'weechat', stop reason = signal SIGABRT
  * frame #0: 0x00007f59854cf664 libc.so.6`__pthread_kill_implementation + 276
    frame #1: 0x00007f5985476c4e libc.so.6`raise + 30
    frame #2: 0x00007f598545e902 libc.so.6`abort + 223
    frame #3: 0x00007f5976458d6a
    frame #4: 0x00007f5976458d59
    frame #5: 0x00007f59765dffc9
    frame #6: 0x00007f59765e5c49
    frame #7: 0x00007f59765e590a
    frame #8: 0x00007f59765e5899
    frame #9: 0x00007f59765e5886
    frame #10: 0x00007f59756feb62 libmatrix.so`hashbrown::raw::inner::RawTable$LT$T$C$A$GT$::reserve_rehash::h748c97637f651d73 [inlined] core::num::_$LT$impl$u20$u64$GT$::rotate_left::hd2bfee6debea4875 at uint_macros.rs:232:20
    frame #11: 0x00007f59756feb5d libmatrix.so`hashbrown::raw::inner::RawTable$LT$T$C$A$GT$::reserve_rehash::h748c97637f651d73 [inlined] _$LT$core..hash..sip..Sip13Rounds$u20$as$u20$core..hash..sip..Sip$GT$::c_rounds::hd15955d2183ab178(state=<unavailable>) at sip.rs:89:19
    frame #12: 0x00007f59756feb4e libmatrix.so`hashbrown::raw::inner::RawTable$LT$T$C$A$GT$::reserve_rehash::h748c97637f651d73 [inlined] _$LT$core..hash..sip..Hasher$LT$S$GT$$u20$as$u20$core..hash..Hasher$GT$::finish::hd6b6222a58cfb0a1(self=<unavailable>) at sip.rs:321:9
    frame #13: 0x00007f59756feb1e libmatrix.so`hashbrown::raw::inner::RawTable$LT$T$C$A$GT$::reserve_rehash::h748c97637f651d73 [inlined] _$LT$core..hash..sip..SipHasher13$u20$as$u20$core..hash..Hasher$GT$::finish::hcee35528a7a42b2a at sip.rs:247:9
    frame #14: 0x00007f59756feb1e libmatrix.so`hashbrown::raw::inner::RawTable$LT$T$C$A$GT$::reserve_rehash::h748c97637f651d73 [inlined] _$LT$std..hash..random..DefaultHasher$u20$as$u20$core..hash..Hasher$GT$::finish::h45e1d59f0a310c72(self=<unavailable>) at random.rs:143:16
    frame #15: 0x00007f59756feb1e libmatrix.so`hashbrown::raw::inner::RawTable$LT$T$C$A$GT$::reserve_rehash::h748c97637f651d73 [inlined] hashbrown::map::make_hash::hce10f73195e40ba6(hash_builder=<unavailable>, val=<unavailable>) at map.rs:254:5
    frame #16: 0x00007f59756fe98d libmatrix.so`hashbrown::raw::inner::RawTable$LT$T$C$A$GT$::reserve_rehash::h748c97637f651d73 [inlined] hashbrown::map::make_hasher::_$u7b$$u7b$closure$u7d$$u7d$::h82487d03f6a26073(val=<unavailable>) at map.rs:218:16
    frame #17: 0x00007f59756fe98d libmatrix.so`hashbrown::raw::inner::RawTable$LT$T$C$A$GT$::reserve_rehash::h748c97637f651d73 [inlined] hashbrown::raw::inner::RawTable$LT$T$C$A$GT$::reserve_rehash::_$u7b$$u7b$closure$u7d$$u7d$::hf17abcc8719b1c0b(table=0x00007fff580e4020, index=1) at mod.rs:682:33
    frame #18: 0x00007f59756fe985 libmatrix.so`hashbrown::raw::inner::RawTable$LT$T$C$A$GT$::reserve_rehash::h748c97637f651d73 [inlined] hashbrown::raw::inner::RawTableInner$LT$A$GT$::rehash_in_place::hf5d0fe7e9c994669(self=0x00007fff580e4020, hasher=<unavailable>, size_of=40, drop=<unavailable>) at mod.rs:1506:28
    frame #19: 0x00007f59756fe835 libmatrix.so`hashbrown::raw::inner::RawTable$LT$T$C$A$GT$::reserve_rehash::h748c97637f651d73 [inlined] hashbrown::raw::inner::RawTableInner$LT$A$GT$::reserve_rehash_inner::h3467793440923440(self=0x00007fff580e4020, additional=1, hasher=<unavailable>, fallibility=Infallible, layout=(size = 40, ctrl_align = 16), drop=<unavailable>) at mod.rs:1398:13
    frame #20: 0x00007f59756fe511 libmatrix.so`hashbrown::raw::inner::RawTable$LT$T$C$A$GT$::reserve_rehash::h748c97637f651d73(self=0x00007fff580e4020, additional=1, hasher=<unavailable>, fallibility=Infallible) at mod.rs:680:13
```

**Comment by panekj** [comment]
Currently it worked until something happened in serde, will have to debug further what it didn't like (looks like malloc failed?)
```
(lldb) bt
* thread #1, name = 'weechat', stop reason = signal SIGABRT
  * frame #0: 0x00007f61a9618664 libc.so.6`__pthread_kill_implementation + 276
    frame #1: 0x00007f61a95bfc4e libc.so.6`raise + 30
    frame #2: 0x00007f61a95a7902 libc.so.6`abort + 223
    frame #3: 0x00007f619a7e4bca
    frame #4: 0x00007f619a7e4bb9
    frame #5: 0x00007f619a9700b9
    frame #6: 0x00007f619a975e7c
    frame #7: 0x00007f619a975b4a
    frame #8: 0x00007f619a975ad9
    frame #9: 0x00007f619a975ac6
    frame #10: 0x00007f619a164272 libmatrix.so`_$LT$serde..__private..de..content..ContentDeserializer$LT$E$GT$$u20$as$u20$serde..de..Deserializer$GT$::deserialize_string::h197ec2c5f1c85851 [inlined] std::sys::pal::unix::alloc::_$LT$impl$u20$core..alloc..global..GlobalAlloc$u20$for$u20$std..alloc..System$GT$::dealloc::h6215a2316411bfb8 at alloc.rs:48:9
    frame #11: 0x00007f619a164268 libmatrix.so`_$LT$serde..__private..de..content..ContentDeserializer$LT$E$GT$$u20$as$u20$serde..de..Deserializer$GT$::deserialize_string::h197ec2c5f1c85851 [inlined] __rdl_dealloc at alloc.rs:408:25
    frame #12: 0x00007f619a164268 libmatrix.so`_$LT$serde..__private..de..content..ContentDeserializer$LT$E$GT$$u20$as$u20$serde..de..Deserializer$GT$::deserialize_string::h197ec2c5f1c85851 [inlined] alloc::alloc::dealloc::h0c7f723beeea303c at alloc.rs:119:14
    frame #13: 0x00007f619a164268 libmatrix.so`_$LT$serde..__private..de..content..ContentDeserializer$LT$E$GT$$u20$as$u20$serde..de..Deserializer$GT$::deserialize_string::h197ec2c5f1c85851 [inlined] _$LT$alloc..alloc..Global$u20$as$u20$core..alloc..Allocator$GT$::deallocate::hf77059ee2f7db3b5(self=<unavailable>, ptr=<unavailable>, layout=<unavailable>) at alloc.rs:256:22
    frame #14: 0x00007f619a164268 libmatrix.so`_$LT$serde..__private..de..content..ContentDeserializer$LT$E$GT$$u20$as$u20$serde..de..Deserializer$GT$::deserialize_string::h197ec2c5f1c85851 [inlined] _$LT$alloc..raw_vec..RawVec$LT$T$C$A$GT$$u20$as$u20$core..ops..drop..Drop$GT$::drop::h1e9dbd0cbc22bd93(self=<unavailable>) at raw_vec.rs:583:22
    frame #15: 0x00007f619a16425f libmatrix.so`_$LT$serde..__private..de..content..ContentDeserializer$LT$E$GT$$u20$as$u20$serde..de..Deserializer$GT$::deserialize_string::h197ec2c5f1c85851 [inlined] core::ptr::drop_in_place$LT$alloc..raw_vec..RawVec$LT$u8$GT$$GT$::h89a16fffcccb95c8((null)=<unavailable>) at mod.rs:542:1
    frame #16: 0x00007f619a16425f libmatrix.so`_$LT$serde..__private..de..content..ContentDeserializer$LT$E$GT$$u20$as$u20$serde..de..Deserializer$GT$::deserialize_string::h197ec2c5f1c85851 [inlined] core::ptr::drop_in_place$LT$alloc..vec..Vec$LT$u8$GT$$GT$::hc305748c741fa210((null)=<unavailable>) at mod.rs:542:1
    frame #17: 0x00007f619a16425f libmatrix.so`_$LT$serde..__private..de..content..ContentDeserializer$LT$E$GT$$u20$as$u20$serde..de..Deserializer$GT$::deserialize_string::h197ec2c5f1c85851 [inlined] _$LT$serde..de..impls..StringVisitor$u20$as$u20$serde..de..Visitor$GT$::visit_byte_buf::hedfa9204ce0441a2((null)=StringVisitor @ 0x00007ffca57393ff, v=<unavailable>) at impls.rs:519:14
    frame #18: 0x00007f619a164233 libmatrix.so`_$LT$serde..__private..de..content..ContentDeserializer$LT$E$GT$$u20$as$u20$serde..de..Deserializer$GT$::deserialize_string::h197ec2c5f1c85851(self=<unavailable>, visitor=StringVisitor @ 0x00007ffca57393ff) at de.rs:1220:40
```

**Comment by poljar** [comment]
Not a real review for now, just wanted to thank you for doing this.

**Comment by panekj** [comment]
No problem, I created both PRs as drafts for now since I'm combing through the codebase trying to map how it works (looks clean and simple to me :) but also because I'm trying to fix the usage first; and once I'm sure that it's usable for others, I'll clean it up for proper review (I don't mind nitpicks and suggestions though).

I'm trying to use matrix solely via weechat, so far the only offenders have been BIG rooms (like `#matrix:matrix.org` which has 62K users; thus the [`d86b41d` (#86)](https://github.com/poljar/weechat-matrix-rs/pull/86/commits/d86b41db185833cf39ec304aa0eb7a62873a2187) commit)

**Comment by panekj** [comment]
weird crash a bit after connecting to server
Process 327172 stopped
* thread #1, name = 'weechat', stop reason = signal SIGABRT
    frame #0: 0x00007f6f1014f664 libc.so.6`__pthread_kill_implementation + 276
libc.so.6`__pthread_kill_implementation:
->  0x7f6f1014f664 <+276>: movl   %eax, %ebx
    0x7f6f1014f666 <+278>: negl   %ebx
    0x7f6f1014f668 <+280>: cmpl   $0xfffff000, %eax ; imm = 0xFFFFF000
    0x7f6f1014f66d <+285>: movl   $0x0, %eax
(lldb) bt
* thread #1, name = 'weechat', stop reason = signal SIGABRT
  * frame #0: 0x00007f6f1014f664 libc.so.6`__pthread_kill_implementation + 276
    frame #1: 0x00007f6f100f6c4e libc.so.6`raise + 30
    frame #2: 0x00007f6f100de902 libc.so.6`abort + 223
    frame #3: 0x00007f6f010883ea libmatrix.so`hyper::client::client::Client$LT$C$C$B$GT$::request::h9877a54de8b38a42 [inlined] alloc::boxed::Box$LT$T$GT$::new::he91992771fd9f17f(x={async_fn_env#0}<reqwest::connect::Connector, reqwest::async_impl::body::ImplStream> @ 0x00000000116cb780) at boxed.rs:259:18
    frame #4: 0x00007f6f010882e4 libmatrix.so`hyper::client::client::Client$LT$C$C$B$GT$::request::h9877a54de8b38a42 [inlined] alloc::boxed::Box$LT$T$GT$::pin::hacac54dde67df212 at boxed.rs:326:9
    frame #5: 0x00007f6f010882e4 libmatrix.so`hyper::client::client::Client$LT$C$C$B$GT$::request::h9877a54de8b38a42 [inlined] hyper::client::client::ResponseFuture::new::h8996a91a988931f6 at client.rs:589:37
    frame #6: 0x00007f6f010882e4 libmatrix.so`hyper::client::client::Client$LT$C$C$B$GT$::request::h9877a54de8b38a42(self=<unavailable>, req=Request<reqwest::async_impl::body::ImplStream> @ 0x000055c2c6718000) at client.rs:189:9
    frame #7: 0x000055c28de535d5 weechat`eval_replace_vars_cb + 709
(lldb) continue
Process 327172 resuming
Process 327172 exited with status = -1 (0xffffffff) lost connection
```

**Comment by panekj** [comment]
Need to figure what I broke or if matrix.org changed something recently because it does not load new messages, only grabbing backlog via PageUp works (and misses out on few last messages)

**Comment by panekj** [comment]
Also since matrix.org switched to authenticated media, I'm not exactly sure how to handle the mxc URLs since putting the token in query is not advised (also super bad)

**Comment by poljar** [comment]
> Also since matrix.org switched to authenticated media, I'm not exactly sure how to handle the mxc URLs since putting the token in query is not advised (also super bad)

Yeah, you would probably need a small helper of some sort which knows the access token, or you could keep it in the query and the small helper puts the token into the header. Ideally we would also use the URL escape code so we hide all the unnecessary data the URL needs to contain.

**Comment by panekj** [comment]
> Need to figure what I broke or if matrix.org changed something recently because it does not load new messages, only grabbing backlog via PageUp works (and misses out on few last messages)

Fixed now

**Pull request merged**
